; PlatformIO Project Configuration File
;
;   Build options: build flags, source filter
;   Upload options: custom upload port, speed and extra flags
;   Library options: dependencies, extra library storages
;   Advanced options: extra scripting
;
; Please visit documentation for the other options and examples
; https://docs.platformio.org/page/projectconf.html

[env:uno]
platform = atmelavr
board = uno
framework = arduino
monitor_speed = 115200
; upload_port = /dev/cu.usbserial-1430   ; optional
; If your UNO appears as /dev/cu.usbserial-1430 (as detected earlier) you can
; either pass --upload-port /dev/cu.usbserial-1430 to the upload command or
; uncomment the line below to hardcode it here for convenience.
; upload_port = /dev/cu.usbserial-1430
